app/recomendation/views.py
from flask import Blueprint, render_template, request
from app.models import filter_by_many_values_perfect

recomendation = Blueprint("recomendation", __name__,
                          url_prefix='/recomendation')

"""
    This module recomends a car based on a users preferences
    if the following values are choosen for the preferences he 
    choose.
"""
budget = {"cheap": 1000000, "affordable": 3000000, "luxury": 3000000}
seatnumber = [2, 4, 5, 6, 7, 8]
use = {"daily": 18, "weekly": 15, "occasionaly": 10}


@recomendation.route('/', methods=['post', 'get'])
def recomendation_steps():
    return render_template("recomendation/find.html")


@recomendation.route('/result', methods=["POST", "GET"])
def recomendation_result():
    """
        This function will filter out cars from the db
        according to the preferences of the user
    """
    form = request.form
    choices = {}
    conditions = []
    if request.method == "POST" and len(form) == 3:
        for key in form.keys():
            k = key.split(":")
            choices[k[0]] = k[1]
        if choices['budget'] == 'luxury':
            conditions.append({"start_price": {'$gte': budget['luxury']}})
            conditions.append({"SeatCapacity": {'$gte': seatnumber[seatnumber.index(int(choices['seatnumber']))]}})
        elif choices['budget'] == 'cheap':
            conditions.append({"start_price": {'$lte': budget['cheap']}})
            conditions.append({"SeatCapacity": {'$gte': seatnumber[seatnumber.index(int(choices['seatnumber']))]}})
            conditions.append({"Mileage": {'$gte': use[choices['use']]}})
        elif choices['budget'] == 'affordable':
            conditions.append({"start_price": {'$lte': budget['affordable']}})
            conditions.append({"start_price": {'$gt': budget['cheap']}})
            conditions.append({"SeatCapacity": {'$gte': seatnumber[seatnumber.index(int(choices['seatnumber']))]}})
            conditions.append({"Mileage": {'$gte': use[choices['use']]}})
        content=filter_by_many_values_perfect(conditions).limit(4)
        return render_template("recomendation/findresult.html", content=content)
    else:
        return render_template('recomendation/noresult.html')

app/search/views.py
from flask import Blueprint, render_template, redirect, request,jsonify
from app.models import find_by_car_name,get_details_of_car
import json

search = Blueprint("search", __name__, url_prefix='/search')

# The view function returning the results for a search query


@search.route("/", methods=["POST","GET"])
def search_form():
    """
     search handler for searching the database by carname
     the function expects a form containing an input field
     with name 'search_query' which can be accesed by
     request.form['search_query'] this function will return
     a template containing the results if it's a POST request
    """
    if request.method == 'POST':
        content = find_by_car_name(request.form['search_query'])
        return render_template('search/searchresult.html', result=content,
                               title="Search")
    else:
        return render_template('404.html')


# Ajax Request handler for the search box in landing page


@search.route("/<query>", methods=["GET"])
def ajax_search_form(query=None):
    """
    ajax request handler function it takes urls like
    /search/<query>
    Eg. /search/Alto
    This will look up the database to find details of
    a car with name Alto
    it uses a function in models.py which returns a cursor
    the results from database it is encoded as JSON an returned to
    a JS function
    :param query:
    :return:JSON Data
    """
    if query is not None:
        content = find_by_car_name(query)
        car_name_list = [{"carname":car['carname']} for car in content]
        return json.dumps(car_name_list)


@search.route("/getcardetails/<carname>",methods=["GET"])
def get_car_details_by_name(carname=None):
    """
    Fetch all details avialable for a car from database
    expects a url like this
    /search/cardetails/Maruti Alto 800
    :param carname:
    :return: rendered template cardetails.html
    """
    if carname is not None:
        details = get_details_of_car(carname)
        return render_template("search/searchspec.html",details=details,found=True)
    else:
        return render_template("search/searchspec.html", found=False)

app/templates/recomendation/find.html
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<!-- Font Styles -->
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:100|Raleway" rel="stylesheet">
        <link rel="shortcut icon" href="../favicon.ico">
        <link rel="stylesheet" type="text/css" href="../static/css/normalize.css" />
		<link rel="stylesheet" type="text/css" href="../static/css/demo.css" />
        <link rel="stylesheet" type="text/css" href="../static/css/component.css" />
        <!-- Compiled and minified CSS -->
        
     
        <script   src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
        <script src="../static/js/modernizr.custom.js"></script>
        <title>GaadiNation</title>
	</head>
	<body>
			<div>
				<form method='post' class="ac-custom ac-radio ac-fill" autocomplete="off" action="{{ url_for('recomendation.recomendation_result') }}">
                    <section id="budget">
					<h2>What's your budget?</h2>
					<ul>
                        <li><input id="r1" name="budget:cheap" type="radio"><label for="r1"><font color="white"  style="font-family:Raleway;">Cheap</font></label></li>
						<li><input id="r2" name="budget:affordable" type="radio"><label for="r2"><font color="white">Affordable</font></label></li>
                        <li><input id="r3" name="budget:luxury" type="radio"><label for="r3"><font color="white">Luxury</font></label></li>
					</ul>
                    </section>
                    <section id="seatnumber">
                    <h2>How many people do you usually travel with?</h2>
                    <ul>
						<li><input id="r5" name="seatnumber:4" type="radio"><label for="r5"><font color="white">4</font></label></li>
						<li><input id="r6" name="seatnumber:5" type="radio"><label for="r6"><font color="white">5</font></label></li>
						<li><input id="r7" name="seatnumber:6" type="radio"><label for="r7"><font color="white">6</font></label></li>
						<li><input id="r8" name="seatnumber:8" type="radio"><label for="r8"><font color="white">8</font></label></li>
					</ul>
                    </section>
                    <section id="use">  
                    <h2>How often do you use your car?</h2>
                    <ul>
						<li><input id="r9" name="use:daily" type="radio"><label for="r9"><font color="white">Daily</font></label></li>
						<li><input id="r10" name="use:weekly" type="radio"><label for="r10"><font color="white">Weekly</font></label></li>
						<li><input id="r11" name="use:occasionaly" type="radio"><label for="r11"><font color="white">Occasionally</font></label></li>
				   </ul>
                   </section>

			</div>
        <center><button class="fs-submit" type="submit">Find Car</button></center>
        </form>
		</div><!-- /container -->
		<!-- Navigation Button -->
            <div class="row" style="margin-left:95%;">
                 <a href="/home" class="btn-floating btn-large waves-effect waves-light white darken-4"><i class="large material-icons blue-grey-text text-darken-4">navigation</i></a>
            </div>
        
		<script src="../static/js/svgcheckbx.js"></script>
	</body>
</html>

app/templates/recomendation/findresult.html
<!DOCTYPE html>
<html>
    <head>
            <!-- Title Of Page -->
            <title>GaadiNation</title>
            
            <!-- Font Styles -->
            <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:100|Raleway|Varela+Round" rel="stylesheet">
            
            <!-- Compiled and minified CSS -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
        
            <!-- Animation Css -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        
            <!--Let browser know website is optimized for mobile -->
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        
            <!-- Icons Css -->
            <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
            <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
            

            <!-- Jquery Library -->
            <script   src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
            
    </head>
    <body>
        <!-- Top NavBar -->
        <div class="navbar-fixed">
            <nav>
                <div class="navbar-fixed blue-grey darken-3">
                    <a href="/home" class="brand-logo center" style="font-family:Alegreya Sans SC;font-size:58px;">Gaadi<span style="color:#43C6DB";>Nation</span></a>
                        <ul id="nav-mobile"  class="left hide-on-med-and-down">
                            <li style="font-family:Raleway;font-size:50px;"><b><a href="/recomendation/">FIND</a></b></li>
                            <li style="font-family:Raleway;font-size:50px;"><b><a href="/compare/">COMPARE</a></b></li>
                            <li style="font-family:Raleway;font-size:50px;"><b><a href="/locate/">LOCATE</a></b></li>
                            <li style="font-family:Raleway;font-size:50px;"><b><a href="/catalog">CATALOG</a></b></li>
                        </ul>
                        <ul id="nav-mobile"  class="right hide-on-med-and-down">
                            <form method="post" action="{{ url_for('search.search_form')}}">
                               
                                    <input id="search" name="search_query" type="search" placeholder="Search Your Car" required>
    
                            </form>
                        </ul>
                </div>
                <ul id="mobile-demo"  class="side-nav">
                            <li style="font-family:Raleway;font-size:50px;"><b><a href="/recomendation">FIND</a></b></li>
                            <li style="font-family:Raleway;font-size:50px;"><b><a href="/compare">COMPARE</a></b></li>
                            <li style="font-family:Raleway;font-size:50px;"><b><a href="/locate">LOCATE</a></b></li>
                            <li style="font-family:Raleway;font-size:50px;"><b><a href="/catalog">CATALOG</a></b></li>
                </ul>
            </nav>
        </div>
        <!-- End Of NavBar-->
        <!--End Of Search Bar-->
        
        <!-- Filter Heading -->
            <div class="row">
                         <h4 class="collapsible-header center-align"><span style="font-family:Alegreya Sans SC;" class="center-align">Recomended Cars</span></h4>
            </div>
        <!-- Filter Heading End-->
        <!-- Find Car Cards-->
        <div class="container">
        <div class="row">
                {% for car in content %}
                <a href="{{url_for('search.get_car_details_by_name',carname=car['carname'])}}">
                 <div style="display:inline-block;width:30%;margin-right:3%;margin-top:4%">
                 <div>
                    <img  src="{{ car['image'] }}" style="max-width: 100%"/>
                  </div>
                    <p class='center-align'>{{car['carname']}}</p>
                 </div>
                </a>
              {% endfor %}
        </div>
        </div>
        <!-- End Of Find Car-->
    
        <!-- Jquery Of Materialise -->
           <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
           <script>
            
              $(document).ready(function(){
                $('.parallax').parallax();
                $('.carousel.carousel-slider').carousel({full_width: true});
            });

             $(document).ready(function(){
                $('.slider').slider({
                    indicators: false,
                    full_width: true,
                    height: 500});
            });
            
            $(document).ready(function(){
                $('.scrollspy').scrollSpy();
            });
               
           </script>
    </body>
</html>

app/templates/recomendation/noresult.html
<!DOCTYPE html>
<html>
    <head>
            <!-- Title Of Page -->
            <title>GaadiNation</title>
            
            <!-- Font Styles -->
            <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:100|Raleway|Varela+Round" rel="stylesheet">
            
            <!-- Compiled and minified CSS -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
        
            <!-- Animation Css -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
            <link rel="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.6.3/font-awesome.min.css" integrity="sha384-Wrgq82RsEean5tP3NK3zWAemiNEXofJsTwTyHmNb/iL3dP/sZJ4+7sOld1uqYJtE" crossorigin="anonymous"> 

        
            <!--Let browser know website is optimized for mobile -->
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        
             <!-- Animation Css -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        
            <!-- Icons Css -->
            <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
            <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
            
            <!-- Jquery Library -->
            <script   src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
            
    </head>
    <body style="background-color:#263238;">
        
        <!-- No Result-->
        <div class="row" style="margin-top: 19%;">
            <center><h3  class="animated infinite pulse white-text" style="font-family:Alegreya Sans SC;">You Haven't Completed Your Questions</h3></center>
             <center><a class="waves-effect waves-light btn" href="/recomendation"><i class="fa fa-car fa-lg"></i></a></center>
        </div>
        <!-- End Of No Result -->
        
         <!-- Jquery Of Materialise -->
           <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
           <script>
            
              $(document).ready(function(){
                $('.parallax').parallax();
                $('.carousel.carousel-slider').carousel({full_width: true});
            });

             $(document).ready(function(){
                $('.slider').slider({
                    indicators: false,
                    full_width: true,
                    height: 500});
            });
            
            $(document).ready(function(){
                $('.scrollspy').scrollSpy();
            });
               
           </script>
    </body>
</html>